# The URL the site will be built for
base_url = "https://williamyoon2021.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "William Yoon"
description = "William Yoon's personal website."

[markdown]
# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "kronuz"
smart_punctuation = true

[extra]
# Theme customization
browser_theme_color = ["#4299e1", "#2b6cb0"]
favicon = "favicon.ico"

# Navigation Menu
menu = [
    { name = "Home", url = "/", trailing_slash = false },
    { name = "About", url = "/about/", trailing_slash = true },
    { name = "Projects", url = "/projects/", trailing_slash = true },
    { name = "Research", url = "/research/", trailing_slash = true },
    { name = "Resume", url = "/resume/", trailing_slash = true },
]

# Footer socials
socials = [
    { name = "GitHub", url = "https://github.com/williamyoon2021" },
    { name = "LinkedIn", url = "https://www.linkedin.com/in/william-yoon-2021/" },
    { name = "Email", url = "mailto:williamyoon2021@gmail.com" },
]

# Security headers
allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'", "'unsafe-inline'"] },
    { directive = "frame-src", domains = ["'self'", "player.vimeo.com", "https://www.youtube-nocookie.com"] },
]

show_reading_time = false 