# On every push this script is executed
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Zola
        run: |
          curl -L https://github.com/getzola/zola/releases/download/v0.18.0/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          echo "$PWD" >> $GITHUB_PATH

      - name: Build and Deploy
        run: |
          zola build
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          cp -r public/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy site"
          git push origin main